# Generated by Django 5.2.7 on 2025-10-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('setor', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('PROTECAO_CABECA', 'Proteção da Cabeça'), ('PROTECAO_AUDITIVA', 'Proteção Auditiva'), ('PROTECAO_RESPIRATORIA', 'Proteção Respiratória'), ('PROTECAO_MÃOS', 'Proteção das Mãos'), ('PROTECAO_PÉS', 'Proteção dos Pés')], max_length=50)),
                ('numero_ca', models.CharField(max_length=50, verbose_name='Número do CA')),
                ('validade_ca', models.DateField(verbose_name='Validade do CA')),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('VENCIDO', 'Vencido')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.epi')),
            ],
        ),
    ]
